### ISSUE TITLE
后端python脚本？

### ISSUE THREAD

**Issue by lihaohong6** [BA-L10N-Viewer/viewer_site#24]
请问作者有意愿公开提取游戏文本的python脚本吗？

我之前写过一个用在[bluearchive.wiki](https://bluearchive.wiki)上的，目前已经生成了所有主线故事（例如[这个](https://bluearchive.wiki/wiki/Main_Story/Volume_3/Chapter_1/Episode_3)）和角色剧情故事（例如[这个](https://bluearchive.wiki/wiki/Mika/Relationship_Story/3)）。处理游戏文件的源代码在[lihaohong6/Blue-Archive-bot](https://github.com/lihaohong6/Blue-Archive-bot)的`story`文件夹里面。我这里也用了AGPL，所以如果您也公开源代码，我们可以互相抄（

**Comment by lihaohong6** [comment]
感谢您的回复！我觉得这个项目比我自己搓的那个有前途，毕竟把剧情文本放到MediaWiki上需要做出很多妥协，但是从头开始做前端受到的限制少很多。

其实发这个issue主要是好奇您是怎么写的。我自己的脚本有不少更新要做，但是都被我鸽了。哪天有空了看看能不能参考一下。

我感觉官方DMCA/律师函对中文项目更严格一些，比如 https://github.com/electricgoat/ba-data 一直没什么事，但是类似的中文社区项目却经常被官方找上门。可能是国际服玩家比国服和日服少，所以发行商也顺带着不怎么管罢。

英语文本的翻译质量堪忧，所以经常有玩家在推上吐槽。我在bluearchive.wiki上自动更新MomoTalk之后经常能见到本地化文本的小改动。

**Comment by sctop** [comment]
谢谢您的支持！~~虽然我是怀疑这项目到底前景有多大，毕竟确实比不过任何现有方案（包括您的）。~~

如果对脚本有什么更多疑问的话，我可以进一步作解释。

由于以上已经讨论过的问题，个人觉得不宜在本issue下讨论脚本的具体问题；同时有鉴于GitHub Issue区的一般使用规范，也不宜在数据repo下单开一个issue进行讨论。所以个人觉得还是在Twitter或者Discord上私信比较好。

考虑到您似乎身处海外，这里贴一下我的Discord账号ID，虽然我个人是不经常使用Discord。

![Screenshot_2024-12-19-23-32-36-767_com.discord-edit.jpg](https://github.com/user-attachments/assets/c47b97cb-76ba-4a24-b5b2-6c3d8e932986)
